# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/WorkSpace/project/FPGA/prj_modelsim/prj_ipdevelop/prj_ipdevelop.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xci
# IP: The module: 'fifo_maxtrix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_modelsim/prj_ipdevelop/prj_ipdevelop.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_modelsim/prj_ipdevelop/prj_ipdevelop.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_modelsim/prj_ipdevelop/prj_ipdevelop.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xci
# IP: The module: 'fifo_maxtrix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_modelsim/prj_ipdevelop/prj_ipdevelop.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_modelsim/prj_ipdevelop/prj_ipdevelop.srcs/sources_1/ip/fifo_maxtrix/fifo_maxtrix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_maxtrix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
