onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/clk
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/resetn
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/vcap_m_axis_tdata
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/vcap_m_axis_tlast
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/vcap_m_axis_tready
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/vcap_m_axis_tuser
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/vcap_m_axis_tvalid
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/cap_tready
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/read_en_dly
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/couts
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/isp_rgb_tlast
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/isp_rgb_tready
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/isp_rgb_tuser
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/isp_rgb_tvalid
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/isp_rgb_tdata
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/file_data
add wave -noupdate -group tb_img /glbl/top_tb_i/tb_img_I/read_file_valid
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/clk
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/read_en
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/data_valid
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/data_out
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/read_count
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/rd_data
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/valid_reg
add wave -noupdate -group read_file /glbl/top_tb_i/tb_img_I/read_file_i/data_rd
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/pixel_clk
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/rst_n
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tdata
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tlast
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tready
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tuser
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tvalid
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/debug_cmd
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayerType
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tlast
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tready
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tuser
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tvalid
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tdata
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tdata_dely
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tlast_dely
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tuser_dely
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/s_axis_tvalid_dely
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/debug_cmd_dely
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tlast_reg
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tuser_reg
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tvalid_reg
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/m_axis_tdata_reg
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_matrix_tlast
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_matrix_tuser
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_matrix_tvalid
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_matrix_01
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_matrix_11
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_matrix_21
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_axis_tlast
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_axis_tuser
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_axis_tvalid
add wave -noupdate -group isp_rgb_model /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/bayer2rgb_axis_tdata
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/pixel_clk
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data01
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data11
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data21
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/bayerType
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/m_axis_tlast
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/m_axis_tuser
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/m_axis_tvalid
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/m_axis_tdata
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/bayer_type
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly3
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly4
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly5
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly6
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tlast_dly7
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly3
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly4
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly5
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly6
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tuser_dly7
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly3
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly4
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly5
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly6
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/s_axis_tvalid_dly7
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data01_dly1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data01_dly2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data01_dly3
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data11_dly1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data11_dly2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data11_dly3
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data21_dly1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data21_dly2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix_data21_dly3
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data00
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data01
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data02
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data10
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data11
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data12
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data20
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data21
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix0_data22
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data00
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data01
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data02
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data10
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data11
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data12
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data20
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data21
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/matrix1_data22
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data00
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data01
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data02
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data10
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data11
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data12
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data20
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data21
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data22
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/dataout
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/RGB_reg
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/G_odd
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/G_even
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/line_cout
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/pixels_cout
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/tmp_odd
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/line_odd
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/tvalid
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data_reg0
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data_reg1
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/data_reg2
add wave -noupdate -group byaer2rgb /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/U_bayer2rgb/G_flg
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/clk
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/write_en
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/stop_en
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/data_in
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/done
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/write_count
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/done_reg
add wave -noupdate -group write_file /glbl/top_tb_i/tb_img_I/write_file_0/data_wr0
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/clk
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/write_en
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/stop_en
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/data_in
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/done
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/write_count
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/done_reg
add wave -noupdate -group write_file_1 /glbl/top_tb_i/tb_img_I/write_file_1/data_wr0
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/pixel_clk
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/rst_n
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tdata
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tlast
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tuser
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tvalid
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/m_axis_tlast
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/m_axis_tuser
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/m_axis_tvalid
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/matrix_01
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/matrix_11
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/matrix_21
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/start_flg
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_count
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/tvalid_reg
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tlast_dly1
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tuser_dly1
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tvalid_dly1
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tdata_dly1
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tlast_dly2
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tuser_dly2
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tvalid_dly2
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tdata_dly2
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tlast_dly3
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tuser_dly3
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tvalid_dly3
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/s_axis_tdata_dly3
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_0_tlast
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_0_tuser
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_0_tvalid
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_0_tdata
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_tlast
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_tuser
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_tvalid
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_tdata
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_CE
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_D
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_Q
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_tlast
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_tuser
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_tvalid
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_tdata
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_Q
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_dout_2
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_dout_1
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_rd
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_rd
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_wr_ctrl
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1_rd_ctrl
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_wr_ctrl
add wave -noupdate -group maxtri3x3 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2_rd_ctrl
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/clk
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/srst
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/din
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/wr_en
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/rd_en
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/dout
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/full
add wave -noupdate -group line_buff1 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_1/empty
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/clk
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/srst
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/din
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/wr_en
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/rd_en
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/dout
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/full
add wave -noupdate -group line_buff2 /glbl/top_tb_i/tb_img_I/isp_rgb_model_I/maxtri3x3_bayer2rgb/line_buff_2/empty
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {720000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 594
configure wave -valuecolwidth 219
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {27583840256 ps}
